export default function Products() {
  const products = [
    {
      name: 'AiCheck',
      tagline: 'Intelligence at Every Checkpoint',
      description:
        'AiCheck is a mobile application that accurately determines whether a photo or video was generated by AI or captured by a human. It provides a clear probability score, allowing users to assess the authenticity of visual content with confidence.',
      features: ['AI-powered verification', 'Real-time processing', 'Enterprise-grade security', 'Seamless integrations'],
      accent: '#FF6B35',
      icon: (
        <svg viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg" className="w-10 h-10">
          <path d="M24 4L28.5 16L40 20L28.5 24L24 36L19.5 24L8 20L19.5 16L24 4Z" fill="#FF6B35" />
          <circle cx="36" cy="36" r="8" stroke="#FF6B35" strokeWidth="2" />
          <path d="M32 36L35 39L40 33" stroke="#FF6B35" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
        </svg>
      ),
      badge: 'AI Detection Tool',
    },
    {
      name: 'GroupLink',
      tagline: 'Connections That Actually Matter',
      description:
        'GroupLink reimagines how communities form, communicate, and grow. A platform engineered for meaningful group interactions — from intimate teams to expansive networks.',
      features: ['Smart group matching', 'Rich communication tools', 'Community analytics', 'Cross-platform sync'],
      accent: '#7C6FFF',
      icon: (
        <svg viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg" className="w-10 h-10">
          <circle cx="16" cy="20" r="6" stroke="#7C6FFF" strokeWidth="2" />
          <circle cx="32" cy="20" r="6" stroke="#7C6FFF" strokeWidth="2" />
          <circle cx="24" cy="32" r="6" stroke="#7C6FFF" strokeWidth="2" />
          <line x1="20" y1="24" x2="24" y2="26" stroke="#7C6FFF" strokeWidth="2" />
          <line x1="28" y1="24" x2="24" y2="26" stroke="#7C6FFF" strokeWidth="2" />
        </svg>
      ),
      badge: 'Location Sharing Platform',
    },
  ]

  return (
    <section id="technologies" className="py-32 px-6 relative">
      {/* Section label */}
      <div className="max-w-7xl mx-auto">
        <div className="mb-16 flex flex-col md:flex-row md:items-end md:justify-between gap-4">
          <div>
            <p className="text-ember-400 text-xs font-display font-600 tracking-widest uppercase mb-3">TECHNOLOGIES</p>
            <h2 className="font-display font-800 text-white text-4xl md:text-5xl leading-tight">
              Multiple platforms.<br />One vision.
            </h2>
          </div>
          <p className="font-body font-300 text-mist max-w-sm leading-relaxed text-sm">
            Each product under Eldia Enterprises is purpose-built — not a feature, not an afterthought. Standalone platforms that define their categories.
          </p>
        </div>

        {/* Product cards */}
        <div className="grid md:grid-cols-2 gap-6">
          {products.map((product, i) => (
            <div
              key={product.name}
              className="group relative rounded-2xl border border-white/5 bg-steel p-8 md:p-10 overflow-hidden transition-all duration-300 hover:border-white/10 hover:-translate-y-1"
            >
              {/* Card glow on hover */}
              <div
                className="absolute inset-0 opacity-0 group-hover:opacity-100 transition-opacity duration-500 pointer-events-none"
                style={{ background: `radial-gradient(ellipse at 50% 0%, ${product.accent}10 0%, transparent 70%)` }}
              />

              {/* Top row */}
              <div className="flex items-start justify-between mb-6">
                <div className="p-3 rounded-xl border border-white/5 bg-white/5">
                  {product.icon}
                </div>
                <span
                  className="text-xs font-display font-600 px-3 py-1 rounded-full border"
                  style={{ color: product.accent, borderColor: `${product.accent}30`, background: `${product.accent}10` }}
                >
                  {product.badge}
                </span>
              </div>

              {/* Name & tagline */}
              <h3 className="font-display font-700 text-white text-2xl mb-1">{product.name}</h3>
              <p className="font-display font-400 mb-4" style={{ color: product.accent }}>{product.tagline}</p>

              {/* Description */}
              <p className="font-body font-300 text-mist text-sm leading-relaxed mb-8">{product.description}</p>

              {/* Features list */}
              <ul className="space-y-2 mb-8">
                {product.features.map(f => (
                  <li key={f} className="flex items-center gap-3 text-sm font-body text-white/60">
                    <span className="w-1 h-1 rounded-full flex-shrink-0" style={{ background: product.accent }} />
                    {f}
                  </li>
                ))}
              </ul>

              {/* CTA */}
              <a
                href="#contact"
                className="inline-flex items-center gap-2 text-sm font-display font-600 transition-colors duration-200"
                style={{ color: product.accent }}
              >
                Learn more
                <span className="group-hover:translate-x-1 transition-transform duration-200">→</span>
              </a>
            </div>
          ))}
        </div>
      </div>
    </section>
  )
}
