export default function Products() {
  const products = [
    {
      name: 'AiCheck',
      tagline: "Human or AI. Instantly.",
      description:
        'AiCheck is a mobile application designed to determine whether a photo or video was generated by AI or captured by a human. It delivers a clear probability score in real time, allowing users to quickly assess the authenticity of content directly from their screen.',
      features: [
        'Real-time content analysis',
        'Instant probability scoring',
        'Photo & video support',
        'Mobile-first experience',
      ],
      accent: '#F0A832',
      icon: (
        <img
          src="/AiCheck-First-Logo.jpg"
          alt="AiCheck"
          className="w-10 h-10 object-contain rounded-lg"
        />
      ),
      badge: 'AI Detection',
      showCTA: true,
    },
    {
      name: 'GroupLink',
      tagline: 'Connections That Actually Matter',
      description:
        'GroupLink is currently in development, and additional information will be shared in the future.',
      features: [],
      accent: '#7C6FFF',
      icon: (
        <svg
          viewBox="0 0 48 48"
          fill="none"
          xmlns="http://www.w3.org/2000/svg"
          className="w-10 h-10"
        >
          <circle cx="16" cy="20" r="6" stroke="#7C6FFF" strokeWidth="2" />
          <circle cx="32" cy="20" r="6" stroke="#7C6FFF" strokeWidth="2" />
          <circle cx="24" cy="32" r="6" stroke="#7C6FFF" strokeWidth="2" />
          <line x1="20" y1="24" x2="24" y2="26" stroke="#7C6FFF" strokeWidth="2" />
          <line x1="28" y1="24" x2="24" y2="26" stroke="#7C6FFF" strokeWidth="2" />
        </svg>
      ),
      badge: 'Social Platform',
      showCTA: false,
    },
  ];

  return (
    <section id="technologies" className="py-32 px-6 relative">
      <div className="max-w-7xl mx-auto">
        <div className="mb-16 flex flex-col md:flex-row md:items-end md:justify-between gap-4">
          <div>
            <p className="text-ember-400 text-xs font-display font-600 tracking-widest uppercase mb-3">
              Technologies
            </p>
            <h2 className="font-display font-800 text-white text-4xl md:text-5xl leading-tight">
              Two platforms.
              <br />
              One vision.
            </h2>
          </div>
          <p className="font-body font-300 text-mist max-w-sm leading-relaxed text-sm">
            Each product under Eldia Enterprises is purpose-built — not a feature, not an
            afterthought. Standalone platforms that define their categories.
          </p>
        </div>

        <div className="grid md:grid-cols-2 gap-6">
          {products.map((product) => (
            <div
              key={product.name}
              className="group relative rounded-2xl border border-white/5 bg-steel p-8 md:p-10 overflow-hidden transition-all duration-300 hover:border-white/10 hover:-translate-y-1"
            >
              <div
                className="absolute inset-0 opacity-0 group-hover:opacity-100 transition-opacity duration-500 pointer-events-none"
                style={{
                  background: `radial-gradient(ellipse at 50% 0%, ${product.accent}10 0%, transparent 70%)`,
                }}
              />

              <div className="flex items-start justify-between mb-6">
                <div className="p-3 rounded-xl border border-white/5 bg-white/5">
                  {product.icon}
                </div>

                <span
                  className="text-xs font-display font-600 px-3 py-1 rounded-full border"
                  style={{
                    color: product.accent,
                    borderColor: `${product.accent}30`,
                    background: `${product.accent}10`,
                  }}
                >
                  {product.badge}
                </span>
              </div>

              <h3 className="font-display font-700 text-white text-2xl mb-1">
                {product.name}
              </h3>

              <p
                className="font-display font-400 mb-4"
                style={{ color: product.accent }}
              >
                {product.tagline}
              </p>

              <p className="font-body font-300 text-mist text-sm leading-relaxed mb-8">
                {product.description}
              </p>

              {product.features.length > 0 && (
                <ul className="space-y-2 mb-8">
                  {product.features.map((f) => (
                    <li
                      key={f}
                      className="flex items-center gap-3 text-sm font-body text-white"
                    >
                      <span
                        className="w-1 h-1 rounded-full flex-shrink-0"
                        style={{ background: product.accent }}
                      />
                      {f}
                    </li>
                  ))}
                </ul>
              )}

              {product.showCTA && (
                <a
                  href="#contact"
                  className="inline-flex items-center gap-2 text-sm font-display font-600 transition-colors duration-200"
                  style={{ color: product.accent }}
                >
                  Learn more
                  <span className="group-hover:translate-x-1 transition-transform duration-200">
                    {'>'}
                  </span>
                </a>
              )}
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}